<testsuite errors="0" failures="1" name="Django Project Tests" skips="0" tests="1" time="0.003"><testcase classname="authentication.tests.PrivateTes" name="test_ongeza" time="0.000068"><failure message="10 != 13" type="builtins.AssertionError">Traceback (most recent call last):
  File "/baratel/authentication/tests.py", line 9, in test_ongeza
    self.assertEqual(x, 13)
AssertionError: 10 != 13
</failure></testcase></testsuite>